# SexSpecificScaffolds-FUNCTIONS.R
# functions for testing scaffold depth and variant data for sex chromosome signals

# make_df.sexbias() a function to build the df.sexbias dataframe
# depth and variant calls from read mapping against hardmasked assembly
# takes a list of 5 filenames, all generated by Ceres scripts: 
#   nmasked: nmasked.csv file with per-scaffold lengths and masked bp counts
#   depthF: depth_per_scaffold.tsv from female reads against hardmasked assembly
#   depthM: depth_per_scaffold.tsv from male reads against hardmasked assembly
#   nvariF: nseg_per_scaffold.csv from female reads, count of variant sites of hardmasked scaffolds
#   nvariM: nseg_per_scaffold.csv from male reads, count of variant sites of hardmasked scaffolds
# reads in all files, sorts by scaffold length, calculates for each scaffold:
#   - total length, masked bp, unmasked length
#   - proportion of total assembly length
#   - proportion of unmasked assembly length
#   - female and male normalized depths (to unmasked length-weighted average depth)
#   - female and male frequency of variant sites
#   - F/M ratio of normalized depth
#   - F/M ratio of variant frequency 
make_df.sexbias <- function(l.IN_FILES){
  # get scaffolds and lengths from asm fasta index
  NMASKED <- read.csv(l.IN_FILES$nmasked, header = F,
                      col.names = c('scaffold', 'length', 'masked'))
  NMASKED$unmasked <- NMASKED$length - NMASKED$masked
  NMASKED <- NMASKED[order(-NMASKED$unmasked),]
  # input dataframes
  IN_DEPTHF <- read.table(l.IN_FILES$depthF, header = F, row.names = 1, 
                          col.names = c('scaffold', 'depth'))
  IN_DEPTHM <- read.table(l.IN_FILES$depthM, header = F, row.names = 1, 
                          col.names = c('scaffold', 'depth'))
  IN_NVARIF <- read.csv(l.IN_FILES$nvariF, header = F, row.names = 1, 
                        col.names = c('scaffold','n_variants'))
  IN_NVARIM <- read.csv(l.IN_FILES$nvariM, header = F, row.names = 1, 
                        col.names = c('scaffold','n_variants'))
  # scaffolds ordered by length
  SCAFFOLDS <- NMASKED$scaffold
  # start output df ordered by scaffold length
  SEXBIAS <- data.frame(length = NMASKED$length,
                        masked = NMASKED$masked,
                        unmasked = NMASKED$unmasked,
                        depthF = IN_DEPTHF[SCAFFOLDS,],
                        depthM = IN_DEPTHM[SCAFFOLDS,],
                        n_varF = IN_NVARIF[SCAFFOLDS,],
                        n_varM = IN_NVARIM[SCAFFOLDS,],
                        row.names = SCAFFOLDS)
  # treat missing values as 0
  SEXBIAS[is.na(SEXBIAS)] = 0
  # proportion of total length per scaffold
  SEXBIAS$pr_length <- SEXBIAS$length / sum(SEXBIAS$length)
  # proportion of unmasked length per scaffold
  SEXBIAS$pr_unmasked <- SEXBIAS$unmasked / sum(SEXBIAS$unmasked)
  # unmasked length-weighted normalized depths
  SEXBIAS$depthF_n <- SEXBIAS$depthF / sum(SEXBIAS$depthF * SEXBIAS$pr_unmasked)
  SEXBIAS$depthM_n <- SEXBIAS$depthM / sum(SEXBIAS$depthM * SEXBIAS$pr_unmasked)
  # frequency of variant sites per kb
  SEXBIAS$fr_varF <- 1000 * SEXBIAS$n_varF / SEXBIAS$unmasked
  SEXBIAS$fr_varM <- 1000 * SEXBIAS$n_varM / SEXBIAS$unmasked
  # frequency of variants per kb, normalized to library average
  SEXBIAS$fr_varF_n <- SEXBIAS$fr_varF / (1000 * sum(SEXBIAS$n_varF)/sum(SEXBIAS$unmasked))
  SEXBIAS$fr_varM_n <- SEXBIAS$fr_varM / (1000 * sum(SEXBIAS$n_varM)/sum(SEXBIAS$unmasked))
  # sex bias (female / male)
  SEXBIAS$Depth_bias <- SEXBIAS$depthF_n / SEXBIAS$depthM_n
  SEXBIAS$FrVar_bias <- SEXBIAS$fr_varF_n / SEXBIAS$fr_varM_n
  
  return(SEXBIAS)
  
}


# Function to combine stats from df.SexBias across list of scaffolds
# Used in make_df.HomologSexBias() inside sapply call
ClusterStats <- function(SCAF_LIST, DF.SEXBIAS){
  cbind( nscafs = length(SCAF_LIST), 
         longest = SCAF_LIST[order(-DF.SEXBIAS[SCAF_LIST,]$length)][1],
         DF.SEXBIAS[SCAF_LIST,] %>% 
           summarise(total.bp = sum(length), 
                     unmasked.bp = sum(unmasked),
                     pr_length = sum(pr_length),
                     pr_unmasked = sum(pr_unmasked),
                     depth_raw.F = sum(unmasked*depthF/sum(unmasked)),
                     depth_raw.M = sum(unmasked*depthM/sum(unmasked)),
                     var_count.F = sum(n_varF), 
                     var_count.M = sum(n_varM),
                     var_fr.F = sum(n_varF)/sum(unmasked),
                     var_fr.M = sum(n_varM)/sum(unmasked),
                     depth_n.F = sum(unmasked*depthF_n/sum(unmasked)), 
                     depth_n.M = sum(unmasked*depthM_n/sum(unmasked)), 
                     var_n.F = sum(unmasked*fr_varF_n/sum(unmasked)), 
                     var_n.M = sum(unmasked*fr_varM_n/sum(unmasked)))
  )
}

# function to make df with composite stats for homolog clusters
# takes homolog cluster list from alignment_region_dotplot-FUNCTIONS.R GetHomologs()
#  (my convention in those alignments is ref=M qry=F)
# takes DF.SEXBIAS for each sex from make_df.sexbias
make_df.HomologSexBias <- function(CLUSTERS, DF.SEXBIAS.F, DF.SEXBIAS.M){
  
  DF.HOMOLOGS.F <- sapply(CLUSTERS, function(x){ 
      ClusterStats(x$QryScafs, DF.SEXBIAS.F) 
    }) %>% t() %>% data.frame()
  
  DF.HOMOLOGS.M <- sapply(CLUSTERS, function(x){
      ClusterStats(x$RefScafs, df.SexBias.M )
    }) %>% t() %>% data.frame()
  
  DF.HOMOLOGS <- data.frame(
    F_longest = unlist(DF.HOMOLOGS.F$longest),
    F_nscafs = unlist(DF.HOMOLOGS.F$nscafs),
    F_total.bp = unlist(DF.HOMOLOGS.F$total.bp),
    F_unmasked = unlist(DF.HOMOLOGS.F$unmasked.bp),
    F_pr.length = unlist(DF.HOMOLOGS.F$pr_length),
    F_pr.unmasked = unlist(DF.HOMOLOGS.F$pr_unmasked),
    M_longest = unlist(DF.HOMOLOGS.M$longest),
    M_nscafs = unlist(DF.HOMOLOGS.M$nscafs),
    M_total.bp = unlist(DF.HOMOLOGS.M$total.bp),
    M_unmasked = unlist(DF.HOMOLOGS.M$unmasked),
    M_pr.length = unlist(DF.HOMOLOGS.M$pr_length),
    M_pr.unmasked = unlist(DF.HOMOLOGS.M$pr_unmasked),

    F_depth.raw.F = unlist(DF.HOMOLOGS.F$depth_raw.F),
    F_depth.raw.M = unlist(DF.HOMOLOGS.F$depth_raw.M),
    Fasm_depth.F = unlist(DF.HOMOLOGS.F$depth_n.F),
    Fasm_depth.M = unlist(DF.HOMOLOGS.F$depth_n.M),
    M_depth.raw.F = unlist(DF.HOMOLOGS.M$depth_raw.F),
    M_depth.raw.M = unlist(DF.HOMOLOGS.M$depth_raw.M),
    Masm_depth.F = unlist(DF.HOMOLOGS.M$depth_n.F),
    Masm_depth.M = unlist(DF.HOMOLOGS.M$depth_n.M),
    
    F_var.count.F = unlist(DF.HOMOLOGS.F$var_count.F),
    F_var.count.M = unlist(DF.HOMOLOGS.F$var_count.M),
    F_var.fr.F = unlist(DF.HOMOLOGS.F$var_fr.F),
    F_var.fr.M = unlist(DF.HOMOLOGS.F$var_fr.M),
    Fasm_var.F = unlist(DF.HOMOLOGS.F$var_n.F),
    Fasm_var.M = unlist(DF.HOMOLOGS.F$var_n.M),
    M_var.count.F = unlist(DF.HOMOLOGS.M$var_count.F),
    M_var.count.M = unlist(DF.HOMOLOGS.M$var_count.M),
    M_var.fr.F = unlist(DF.HOMOLOGS.M$var_fr.F),
    M_var.fr.M = unlist(DF.HOMOLOGS.M$var_fr.M),
    Masm_var.F = unlist(DF.HOMOLOGS.M$var_n.F),
    Masm_var.M = unlist(DF.HOMOLOGS.M$var_n.M),
    
    DepthBias_Fasm = (unlist(DF.HOMOLOGS.F$depth_n.F) + 0.001) /
                      (unlist(DF.HOMOLOGS.F$depth_n.M) + 0.001),
    DepthBias_Masm = (unlist(DF.HOMOLOGS.M$depth_n.F) + 0.001) / 
                      (unlist(DF.HOMOLOGS.M$depth_n.M) + 0.001),
    VarBias_Fasm = (unlist(DF.HOMOLOGS.F$var_n.F) + 0.001) / 
                    (unlist(DF.HOMOLOGS.F$var_n.M) + 0.001),
    VarBias_Masm = (unlist(DF.HOMOLOGS.M$var_n.F) + 0.001) / 
                    (unlist(DF.HOMOLOGS.M$var_n.M) + 0.001)
  )
  
  DF.HOMOLOGS$AvgTotalLength <- apply(
    DF.HOMOLOGS[,c('F_total.bp','M_total.bp')], 1, mean, na.rm=T )
  DF.HOMOLOGS$AvgUnmasked <- apply(
    DF.HOMOLOGS[,c('F_unmasked','M_unmasked')], 1, mean, na.rm=T )
  DF.HOMOLOGS$AvgDepthBias <- apply(
    DF.HOMOLOGS[,c('DepthBias_Fasm','DepthBias_Masm')], 1, mean, na.rm=T )
  DF.HOMOLOGS$AvgVarBias <- apply(
    DF.HOMOLOGS[,c('VarBias_Fasm','VarBias_Masm')], 1, mean, na.rm=T )
  
  return(DF.HOMOLOGS[order(-DF.HOMOLOGS$AvgTotalLength),])
}

